<?php
$modversion['name'] = _XTG_MODULE_NAME;
$modversion['version'] = 2.2;
$modversion['description'] = _XTG_MODULE_DESC;
$modversion['credits'] = 'Developed by Xtrem.dj@clubxtrem.net from http://www.clubxtrem.net';
$modversion['author'] = 'xtrem dj and glassJAw';
$modversion['help'] = 'top.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'guestbook_slogo.jpg';
$modversion['dirname'] = 'xtremguestbook';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'xtremguestbook';

//Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Menu
$modversion['hasMain'] = 1;

// Templates
$modversion['templates'][1]['file'] = 'xtremguestbook_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'xtremguestbook_sign.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'xtremguestbook_post.html';
$modversion['templates'][3]['description'] = '';

//Config
$modversion['config'][1]['name'] = 'moderate';
$modversion['config'][1]['title'] = '_XTG_CFG_MODERATE';
$modversion['config'][1]['description'] = '';
$modversion['config'][1]['formtype'] = 'yesno';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = 0;

$modversion['config'][2]['name'] = 'nbmsgbypage';
$modversion['config'][2]['title'] = '_XTG_CFG_NBMSGBYPAGE';
$modversion['config'][2]['description'] = '';
$modversion['config'][2]['formtype'] = 'text';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 10;

$modversion['config'][3]['name'] = 'allowbbcode';
$modversion['config'][3]['title'] = '_XTG_CFG_ALLOWBBCODE';
$modversion['config'][3]['description'] = '';
$modversion['config'][3]['formtype'] = 'yesno';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = 1;

$modversion['config'][4]['name'] = 'allowhtml';
$modversion['config'][4]['title'] = '_XTG_CFG_ALLOWHTML';
$modversion['config'][4]['description'] = '';
$modversion['config'][4]['formtype'] = 'yesno';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = 0;

$modversion['config'][5]['name'] = 'allowsmileys';
$modversion['config'][5]['title'] = '_XTG_CFG_ALLOWSMILEYS';
$modversion['config'][5]['description'] = '';
$modversion['config'][5]['formtype'] = 'yesno';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = 1;

$modversion['config'][6]['name'] = 'sendmail2webmaster';
$modversion['config'][6]['title'] = '_XTG_CFG_SENDMAIL2WEBMASTER';
$modversion['config'][6]['description'] = '';
$modversion['config'][6]['formtype'] = 'yesno';
$modversion['config'][6]['valuetype'] = 'int';
$modversion['config'][6]['default'] = 0;

// Smarty
$modversion['use_smarty'] = 1;

// RMV-NOTIFY
// Notification

$modversion['hasNotification'] = 1;

$modversion['notification']['category'][1]['name'] = 'global';
$modversion['notification']['category'][1]['title'] = _MI_GB_NOTIFY;
$modversion['notification']['category'][1]['description'] = _MI_GB_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = 'index.php';

$modversion['notification']['event'][1]['name'] = 'new_post';
$modversion['notification']['event'][1]['category'] = 'global';
$modversion['notification']['event'][1]['title'] = _MI_GB_NEWPOST_NOTIFY;
$modversion['notification']['event'][1]['caption'] = _MI_GB_NEWPOST_NOTIFYCAP;
$modversion['notification']['event'][1]['description'] = _MI_GB_NEWPOST_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = 'guestbook_newpost_notify';
$modversion['notification']['event'][1]['mail_subject'] = _MI_GB_NEWPOST_NOTIFYSBJ;
